=== rsvato/camldoc-ru/bookinfo.dtd
<!ENTITY chap01 SYSTEM "./chapter01.xml">
<!ENTITY chap02 SYSTEM "./chapter02.xml">
<!ENTITY chap03 SYSTEM "./chapter03.xml">
<!ENTITY chap04 SYSTEM "./chapter04.xml">
<!ENTITY chap05 SYSTEM "./chapter05.xml">
<!ENTITY chap06 SYSTEM "./chapter06.xml">
<!ELEMENT bookinfo (title,subtitle?,authors,legal,part+)>
<!ELEMENT part (title,chap+)>
<!ELEMENT chap (ENTITIES)>
<!ATTLIST chap file CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT authors (main-author,sec-author?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT legal (#PCDATA)>
<!ATTLIST legal year CDATA #IMPLIED>
<!ELEMENT main-author (#PCDATA)>
<!ELEMENT sec-author (#PCDATA)>

=== rsvato/camldoc-ru/bookinfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bookinfo SYSTEM "./bookinfo.dtd">
<bookinfo>
<title>Система Objective Caml, релиз 3.06</title>
<subtitle>Документация и руководство пользователя</subtitle>
<authors>
<main-author>Ксавье Лерой</main-author>
<sec-author>Дамье Долигеc</sec-author>
<sec-author>Жак Гарриг</sec-author>
<sec-author>Дидье Реми</sec-author>
<sec-author>Жером Вуйон</sec-author>
</authors>
<legal year="2002">
	Национальный Институт Исследований в области Информатики и Автоматики
</legal>
<part>
<title>Введение в Objective Caml</title>
<chap file="./chapter01.html">&chap01;</chap>
<chap file="./chapter02.html">&chap02;</chap>
<chap file="./chapter03.html">&chap03;</chap>
<chap file="./chapter04.html">&chap04;</chap>
<chap file="./chapter05.html">&chap05;</chap>
</part>
<part>
	<title>Язык Оbjective Caml</title>
	<chap file="./chapter06.html">&chap06;</chap>
</part>
</bookinfo>
