=== rsvato/camldoc-ru/core.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT abstract (para)>

<!ELEMENT chapter (abstract,main-matters)>
<!ATTLIST chapter
	name CDATA #REQUIRED
	number NMTOKEN #REQUIRED
>

<!ELEMENT command (#PCDATA)>

<!ELEMENT eval-step (user-input,system-response?)>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT lb EMPTY>

<!ELEMENT main-matters (section+)>

<!ELEMENT mdash EMPTY>

<!ELEMENT para (#PCDATA|command|keyword|mdash|term|sub)*>

<!ELEMENT section (subsection|subsection-nonumber|para|session|listing|command-session|list|table)*>
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT subsection (para|session|listing|command-session|list|table)*>
<!ELEMENT subsection-nonumber (para|session|listing|command-session|list|table)*>
<!ATTLIST subsection name CDATA #REQUIRED
		     neednumber NMTOKEN #REQUIRED>
<!ELEMENT session (eval-step+)>
<!ELEMENT command-session (command-line+)>
<!ELEMENT note (para|session)*>
<!ELEMENT system-response (#PCDATA|lb|tab)*>
<!ELEMENT list (item)+>
<!ATTLIST list type CDATA #REQUIRED>
<!ELEMENT item (para)+>
<!ELEMENT table (thead,tbody)>
<!ELEMENT thead (trow)+>
<!ELEMENT tbody (trow)+>
<!ELEMENT trow (tcell)+>
<!ELEMENT tcell (para)+>
<!ELEMENT tab EMPTY>

<!ELEMENT user-input (#PCDATA|lb|tab)*>
<!ELEMENT listing (#PCDATA|lb|tab)*>
<!ELEMENT command-line (input?|response?)*>
<!ELEMENT input (#PCDATA|lb|tab)*>
<!ATTLIST input prompt  CDATA '$'>
<!ELEMENT response (#PCDATA|lb|tab)*>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT term (#PCDATA)>

=== rsvato/camldoc-ru/chapter18.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "./core.dtd">
<chapter name="Интерфейс с C" number="18">
  <abstract>
    <para>В этой главе рассказывается, как написанные на С пользовательские
    примитивы компонуются с кодом Caml и вызываются из функций Caml.</para>
  </abstract>
  <main-matters>
    <section name="Обзор и компиляция">
      <para>Пользовательские примитивы объявляются c помощью ключевого слова
	<command>external</command> в файле реализации или внутри конструкции
	<command>start...end</command> выражения модуля.</para>
      <listing>
	external name : type = C-function-name
      </listing>
      <para>Так определяется имя значения <keyword>name</keyword> типа
      <keyword>type</keyword>, которое выполняется при вызове данной функции С.
	Например, в модуле <command>Pervasive</command> стандартной библиотеки
	примитив <command>input</command> объявлен следующим образом:</para>
      <listing>
	external input: in_channel -&gt; string -&gt; int -&gt; int -&gt; int
	              = "input"
      </listing>
      <para>Примитивы с несколькими аргументами всегда</para>
    </section>
  </main-matters>
</chapter>

=== rsvato/camldoc-ru/chapter11.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE chapter SYSTEM "./core.dtd">
<chapter name="Компиляция во внутренний код (ocamlopt)" number="11">
  <abstract>
    <para>
      В этой главе описывается высокопроизводительный компилятор
      внутреннего кода Objective Caml <command>ocamlopt</command>,
      который компилирует исходные тексты Caml в объектные файлы с
      внутренним кодом и компонует последние в самостоятельные
      исполняемые файлы.</para>
    <para>Этот компилятор доступен не на всех платформах. Генерируемый
      им код работает быстрее байткода, создаваемого
      <command>ocamlc</command>, однако возрастает как время
      компиляции, так и размер исполняемых файлов. Тем не менее,
      совместимость с байткодом исключительно выскока: один и тот же
      код работает одинаково вне зависимости от того, скомпилирован он
      <command>ocamlc</command> или
      <command>ocamlopt</command>.</para>
    <para>Файлы с внутренним кодом нельзя смешивать с файлами с
      байкодом: программа должна быть скомилирована целиком либо
      <command>ocamlc</command>, либо <command>ocamlopt</command>.
      Объектные файлы с внутренним кодом, кроме того, не могут
      загружаться в интерактивную систему
      <command>ocaml</command>.</para>
  </abstract>
  <main-matters>
    <section name="Обзор компилятора">
      <para><command>ocamlopt</command> имеет интерфейс командной
	строки, весьма схожий с <command>ocamlc</command>. Компилятор
	принимает те же типы аргументов: </para>
      
    </section>
  </main-matters>
</chapter>

=== rsvato/camldoc-ru/chapter15.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chapter SYSTEM "core.dtd">
<chapter name="Генератор документации (ocamldoc)" number="15">
  <abstract>
    <para>В этой главе описывается OCamldoc, средство для генерации
      документации из специальных комментариев в исходном тексте
      программ. Такие комментарии записываются в форме <keyword>(**
	... *)</keyword> в соотвествии с форматом, опсианным в разделе
      15.2.</para>
    <para>OCamldoc может генерировать документацию в форматах HTML,
      LaTeX, TeXinfo, страниц руководства Unix и графов зависимостей
      <command>dot</command>. Кроме того, как объясняется в разлеле
      15.3, можно создавать собственные генераторы.</para>
    <para>В этой главе слово <emph>элемент</emph> может означать следующие части исходного текста OCaml: объявление типа, значение, модуль, исключение, </para>
  </abstract>
  <main-matters>
    <section>
    </section>
  </main-matters>
</chapter>

=== rsvato/camldoc-ru/chapter17.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE chapter SYSTEM "core.dtd">
<chapter name="Профилирование (ocamlprof)" number="17">
  <abstract>
    <para>В этой главе рассказывает о профилировании исполнения программ Objective Caml путем записи количества вызовов функций, ветвлений условий и т.д.</para>
  </abstract>
  <main-matters>
    <section name="Компиляция для профилирования">
      <para>Чтобы профилирование выполнение было возможно, программа
	должна компилироваться в специальном режиме с помощью внешнего
	интерфейса к <command>ocamlc</command>
	<command>ocamlp</command> (см. гл. 8). При раздельной
	компиляции именно <command>ocamlp</command> должен
	компилировать модули (т.е. создавать файлы
	<command>.cmo</command>), однако его же можно использовать
	(хотя это и необязательно) для компоновки программы.
    </section>
  </main-matters>
</chapter>
